#!/bin/bash
cd ..
cd memoria
./bin/memoria.out cfg/Memoria_Memoria.cfg
cd ..
cd cpu
./bin/cpu.out cfg/CPU_Memoria.cfg
cd ..
cd fileSystem
./bin/fileSystem.out cfg/FileSystem_Memoria.cfg superbloque.dat
cd ..
cd kernel
./bin/kernel.out cfg/Kernel_Memoria.cfg
cd ..
cd consola
./bin/consola.out cfg/consola_config.cfg
cd ..