#!/bin/bash
cd ..
cd consola
./bin/consola.out cfg/consola_config.cfg include/instrucciones/DEADLOCK_1 && ./bin/consola.out cfg/consola_config.cfg include/instrucciones/DEADLOCK_2 && ./bin/consola.out cfg/consola_config.cfg include/instrucciones/DEADLOCK_3
./bin/consola.out cfg/consola_config.cfg include/instrucciones/DEADLOCK_4