#!/bin/bash
cd ..
cd consola
./bin/consola.out cfg/consola_config.cfg include/instrucciones/BASE_1 && ./bin/consola.out cfg/consola_config.cfg include/instrucciones/BASE_2 && ./bin/consola.out cfg/consola_config.cfg include/instrucciones/BASE_3
