#!/bin/bash
cd ..
cd memoria
./bin/memoria.out cfg/Memoria_Errores.cfg
cd ..
cd cpu
./bin/cpu.out cfg/CPU_Errores.cfg
cd ..
cd fileSystem
./bin/fileSystem.out cfg/FileSystem_Errores.cfg superbloque.dat
cd ..
cd kernel
./bin/kernel.out cfg/Kernel_Errores.cfg
cd ..
cd consola
./bin/consola.out cfg/consola_config.cfg
cd ..